type: yml

application:
  graceful_shutdown_timeout: "2s"
  question:
    questions_count: 6

presence:
  prefix: "presence"
  expiration: "4h"

server:
  http_server:
    port: 80
  grpc_server:
    port: 8088
  websocket_server:
    client:
      read_timeout: "30s"
      write_timeout: "10s"
      ping_period: "60s"
      max_message_size: 512

auth:
  secret: "secret"
  expires_in_minutes: 10080

scheduler:
  match_waited_users_interval_seconds: 5

matching:
  matching_timeout_seconds: 300

redis:
  host: redis

database:
  seeders: "file://repository/mongorepo/seeders"
  migrations: "file://repository/mongorepo/migrations"
  mongodb:
    port: 27017
    host: mongodb
    db_name: db
    username: michael
    password: secret
    migrations: migrations
    duration_seconds: 5
