type: yml

server:
  http_server:
    port: 9090

jwt:
  secret: "secret"

database:
  mongodb:
    port: 27018
    host: localhost
    db_name: db_test
    username: michael_test
    password: secret_test
    migrations: migrations
    duration_seconds: 5
