type: yml

application:
  graceful_shutdown_timeout: "2s"
  websocket:
    read_timeout: "30s"
    write_timeout: "10s"
    ping_period: "60s"
  game:
    questions_count: 6

presence:
  prefix: "presence"
  expiration: "4h"

server:
  http_server:
    port: 80

auth:
  secret: "secret"
  expires_in_minutes: 10080

scheduler:
  match_waited_users_interval_seconds: 5

redis:
  host: redis

database:
  seeders: "file://repository/mongorepo/seeders"
  migrations: "file://repository/mongorepo/migrations"
  mongodb:
    port: 27017
    host: mongodb
    db_name: db
    username: michael
    password: secret
    migrations: migrations
    duration_seconds: 5
