type: yml

presence:
  prefix: "presence"
  expiration: "4h"

server:
  http_server:
    port: 8080

jwt:
  secret: "secretto"

scheduler:
  match_waited_users_interval_seconds: 30

database:
  seeders: "file://repository/mongorepo/seeders"
  migrations: "file://repository/mongorepo/migrations"
  mongodb:
    port: 27017
    host: mongo
    db_name: db
    username: michael
    password: secret
    migrations: migrations
    duration_seconds: 5
