type: yml

server:
  http_server:
    port: 8080

jwt:
  secret: "secret"

database:
  mongodb:
    port: 27017
    host: localhost
    db_name: db
    username: michael
    password: secret
    migrations: migrations
    duration_seconds: 5
