services:
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
    networks:
      - kian
  mongo:
    image: mongo
    restart: always
    ports:
      - '${FORWARD_MONGO_PORT:-27017}:27017'
    volumes:
      - 'mongo:/data/db'
    networks:
      - kian
    environment:
      - MONGO_INITDB_ROOT_USERNAME=michael
      - MONGO_INITDB_ROOT_PASSWORD=secret
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '${FORWARD_APP_PORT:-8080}:8080'
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      REDIS_URL: redis:6379
    networks:
      - kian
    volumes:
      - 'go:/go/pkg'

volumes:
  mongo:
  redis:
  go:

networks:
  kian:
