// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: protobuf/game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStarted) Reset() {
	*x = GameStarted{}
	mi := &file_protobuf_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStarted) ProtoMessage() {}

func (x *GameStarted) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStarted.ProtoReflect.Descriptor instead.
func (*GameStarted) Descriptor() ([]byte, []int) {
	return file_protobuf_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *GameStarted) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type PlayerAnswered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	GameId        string                 `protobuf:"bytes,2,opt,name=GameId,proto3" json:"GameId,omitempty"`
	QuestionId    string                 `protobuf:"bytes,3,opt,name=QuestionId,proto3" json:"QuestionId,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=Answer,proto3" json:"Answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerAnswered) Reset() {
	*x = PlayerAnswered{}
	mi := &file_protobuf_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAnswered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAnswered) ProtoMessage() {}

func (x *PlayerAnswered) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAnswered.ProtoReflect.Descriptor instead.
func (*PlayerAnswered) Descriptor() ([]byte, []int) {
	return file_protobuf_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerAnswered) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlayerAnswered) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *PlayerAnswered) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *PlayerAnswered) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type GameFinished struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=GameId,proto3" json:"GameId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameFinished) Reset() {
	*x = GameFinished{}
	mi := &file_protobuf_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameFinished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFinished) ProtoMessage() {}

func (x *GameFinished) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFinished.ProtoReflect.Descriptor instead.
func (*GameFinished) Descriptor() ([]byte, []int) {
	return file_protobuf_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameFinished) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

var File_protobuf_game_game_proto protoreflect.FileDescriptor

var file_protobuf_game_game_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x22, 0x25, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x51,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x22, 0x26, 0x0a, 0x0c, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x42, 0x16, 0x5a, 0x14, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x61, 0x6d,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_game_game_proto_rawDescOnce sync.Once
	file_protobuf_game_game_proto_rawDescData = file_protobuf_game_game_proto_rawDesc
)

func file_protobuf_game_game_proto_rawDescGZIP() []byte {
	file_protobuf_game_game_proto_rawDescOnce.Do(func() {
		file_protobuf_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_game_game_proto_rawDescData)
	})
	return file_protobuf_game_game_proto_rawDescData
}

var file_protobuf_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_game_game_proto_goTypes = []any{
	(*GameStarted)(nil),    // 0: game.GameStarted
	(*PlayerAnswered)(nil), // 1: game.PlayerAnswered
	(*GameFinished)(nil),   // 2: game.GameFinished
}
var file_protobuf_game_game_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_game_game_proto_init() }
func file_protobuf_game_game_proto_init() {
	if File_protobuf_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_game_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_game_game_proto_goTypes,
		DependencyIndexes: file_protobuf_game_game_proto_depIdxs,
		MessageInfos:      file_protobuf_game_game_proto_msgTypes,
	}.Build()
	File_protobuf_game_game_proto = out.File
	file_protobuf_game_game_proto_rawDesc = nil
	file_protobuf_game_game_proto_goTypes = nil
	file_protobuf_game_game_proto_depIdxs = nil
}
